version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  zastoj:
    build: ./zastoj
    container_name: zastoj
    depends_on:
      - rabbitmq
    network_mode: "host"
    restart: always

  posalji:
    build: ./posalji
    container_name: posalji
    depends_on:
      - rabbitmq 
    restart: always
    tty: true
  
  primi:
    build: ./primi
    container_name: primi
    depends_on:
      - rabbitmq
    restart: always
    tty: true

