version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    

  sender:
    image: python-client
    command: send.py
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    networks:
      - my_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  receiver:
    image: python-client
    command: -u receive.py
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    networks:
      - my_network
    environment:
      - RABBITMQ_HOST=rabbitmq

  processor:
    image: python-client
    command: -u process.py
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - rabbitmq
    networks:
      - my_network
    environment:
      - RABBITMQ_HOST=rabbitmq

networks:
  my_network:
    driver: bridge